apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spark
  name: notebook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook-deployment
  template:
    metadata:
      labels:
        app: notebook-deployment
    spec:
      serviceAccountName: spark
      containers:
      - name: notebook
        image: dataengineeringe2e/spark-jupyter-ubuntu-2.4.4
        ports:
        - containerPort: 8888
        workingDir: /home
      imagePullSecrets:
        - name: dockerlogin
---
apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: notebook-service
spec:
  selector:
    app: notebook-deployment
  ports:
    - protocol: TCP
      port: 29413
  clusterIP: None