init:
	# init project
	terraform init

get:
	# get/update modules
	terraform get --update 

validate:
	# validate syntax
	terraform validate

plan:
	# make a deployment plan (just a plan)
	terraform plan

apply:
	# apply plan
	terraform apply

refresh:
	# reload tf state
	terraform refresh

output:
	# print outputs
	terraform output
